// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'centeredContainer': string;
  'cl': string;
  'error-pre': string;
  'error-values': string;
  'errorKeys': string;
  'errorPre': string;
  'errorTextGeneral': string;
  'errorValues': string;
  'httpStatusCode': string;
  'line-number': string;
  'lineNumber': string;
  'maintenance-hero': string;
  'maintenanceHero': string;
  'slide': string;
}
export const cssExports: CssExports;
export default cssExports;
