// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'App': string;
  'App-header': string;
  'App-link': string;
  'App-logo': string;
  'App-logo-spin': string;
  'app': string;
  'appHeader': string;
  'appLink': string;
  'appLogo': string;
  'appLogoSpin': string;
}
export const cssExports: CssExports;
export default cssExports;
